name: 'Build and Test SBT'
description: 'Build, test et upload artifacts pour projets SBT (inclut setup SBT)'
author: 'Tina Alliche'

inputs:
  # ========================================
  # Setup SBT Inputs (passés à setup-sbt)
  # ========================================
  sbt-version:
    description: 'Version SBT à installer'
    required: false
    default: '1.10.4'
  
  scala-version:
    description: 'Version Scala (pour documentation)'
    required: false
    default: '3.3.1'
  
  java-version:
    description: 'Version Java à configurer'
    required: false
    default: '21'
  
  java-distribution:
    description: 'Distribution Java (temurin, zulu, adopt, etc.)'
    required: false
    default: 'temurin'
  
  artifactory-host:
    description: 'Hostname Artifactory (ex: artifacts.exemple.com)'
    required: false
    default: ''
  
  credentials-realm:
    description: 'Realm Artifactory'
    required: false
    default: 'Artifactory Realm'
  
  repositories-file:
    description: |
      Repositories configuration
      - 'v1' : Legacy avec play2war (défaut)
      - 'v2' : Moderne
      - Chemin custom : 'config/repositories'
    required: false
    default: 'v1'
  
  repositories-content:
    description: 'Configuration repositories inline (YAML)'
    required: false
    default: ''
  
  enable-cache:
    description: 'Activer le cache SBT (ivy2, sbt, coursier)'
    required: false
    default: 'true'
  
  cache-key-prefix:
    description: 'Préfixe des clés de cache'
    required: false
    default: 'sbt'
  
  download-sbt-from:
    description: 'Source téléchargement SBT (github ou custom-url)'
    required: false
    default: 'github'
  
  sbt-download-url:
    description: 'URL custom pour télécharger SBT'
    required: false
    default: ''
  
  working-directory:
    description: 'Répertoire de travail'
    required: false
    default: '.'
  
  # ========================================
  # Build & Test Inputs
  # ========================================
  sbt-commands:
    description: 'Commandes SBT à exécuter'
    required: false
    default: 'clean compile test'
  
  sbt-opts:
    description: 'Options SBT additionnelles (SBT_OPTS)'
    required: false
    default: '-Dsbt.override.build.repos=true -Dsbt.log.noformat=true'
  
  env-vars:
    description: |
      Variables d'environnement additionnelles (format YAML multi-ligne)
      Exemple:
        TZ: America/Montreal
        LANG: en_US.UTF-8
    required: false
    default: ''
  
  continue-on-error:
    description: 'Continue même si les commandes SBT échouent'
    required: false
    default: 'false'
  
  # ========================================
  # Artifact Upload Configuration
  # ========================================
  upload-artifacts:
    description: 'Upload les artifacts vers GitHub Actions'
    required: false
    default: 'true'
  
  artifact-name-prefix:
    description: |
      Préfixe du nom d'artifact
      Si vide, utilise le nom du repository
      Suffixe aléatoire (10 chars) ajouté automatiquement
    required: false
    default: ''
  
  artifact-path:
    description: 'Pattern des fichiers à uploader (compatible glob)'
    required: false
    default: '${{ github.workspace }}/**/target/universal/*.zip'
  
  artifact-retention-days:
    description: 'Jours de rétention des artifacts'
    required: false
    default: '1'
  
  artifact-if-no-files-found:
    description: 'Comportement si aucun fichier trouvé (error/warn/ignore)'
    required: false
    default: 'warn'

outputs:
  action-artifact-name:
    description: 'Nom de l''artifact uploadé (compatible ancien workflow)'
    value: ${{ steps.generate-artifact-name.outputs.artifact-name }}
  
  build-status:
    description: 'Statut du build (success/failure)'
    value: ${{ steps.build.outputs.status }}
  
  artifact-uploaded:
    description: 'Artifact uploadé (true/false)'
    value: ${{ steps.set-upload-status.outputs.uploaded }}
  
  sbt-version:
    description: 'Version SBT installée'
    value: ${{ steps.setup-sbt.outputs.sbt-version }}
  
  cache-hit:
    description: 'Cache restauré (true/false)'
    value: ${{ steps.setup-sbt.outputs.cache-hit }}

runs:
  using: composite
  steps:
    # ========================================
    # Setup SBT (Appelle l'action existante)
    # ========================================
    - name: Setup SBT Environment
      id: setup-sbt
      uses: ../../setup-sbt
      with:
        sbt-version: ${{ inputs.sbt-version }}
        scala-version: ${{ inputs.scala-version }}
        java-version: ${{ inputs.java-version }}
        java-distribution: ${{ inputs.java-distribution }}
        artifactory-host: ${{ inputs.artifactory-host }}
        credentials-realm: ${{ inputs.credentials-realm }}
        repositories-file: ${{ inputs.repositories-file }}
        repositories-content: ${{ inputs.repositories-content }}
        enable-cache: ${{ inputs.enable-cache }}
        cache-key-prefix: ${{ inputs.cache-key-prefix }}
        download-sbt-from: ${{ inputs.download-sbt-from }}
        sbt-download-url: ${{ inputs.sbt-download-url }}
        working-directory: ${{ inputs.working-directory }}
    
    # ========================================
    # Parse Environment Variables
    # ========================================
    - name: Parse Environment Variables
      if: inputs.env-vars != ''
      shell: bash
      run: |
        echo "========================================="
        echo "Parsing Environment Variables"
        echo "========================================="
        
        # Parse YAML format env-vars et les exporte
        while IFS=': ' read -r key value || [ -n "$key" ]; do
          # Skip empty lines and comments
          [[ -z "$key" || "$key" =~ ^[[:space:]]*# ]] && continue
          
          # Trim whitespace
          key=$(echo "$key" | xargs)
          value=$(echo "$value" | xargs)
          
          # Remove quotes if present
          value=$(echo "$value" | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")
          
          if [ -n "$key" ] && [ -n "$value" ]; then
            echo "Setting: $key=$value"
            echo "$key=$value" >> $GITHUB_ENV
          fi
        done <<< "${{ inputs.env-vars }}"
        
        echo ""
        echo "✓ Environment variables configured"
    
    # ========================================
    # Display Environment
    # ========================================
    - name: Display Build Environment
      shell: bash
      run: |
        echo "========================================="
        echo "Build Environment"
        echo "========================================="
        echo "SBT Version: ${{ steps.setup-sbt.outputs.sbt-version }}"
        echo "SBT Path: ${{ steps.setup-sbt.outputs.sbt-path }}"
        echo "Cache Hit: ${{ steps.setup-sbt.outputs.cache-hit }}"
        echo "Working Directory: ${{ inputs.working-directory }}"
        echo ""
        echo "Environment Variables:"
        env | grep -E '^(TZ|LANG|LC_)' || echo "  No special environment variables set"
        echo ""
    
    # ========================================
    # Run SBT Commands
    # ========================================
    - name: Build and Test with SBT
      id: build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: ${{ inputs.continue-on-error == 'true' }}
      env:
        SBT_OPTS: ${{ inputs.sbt-opts }}
      run: |
        echo "========================================="
        echo "Running SBT Commands"
        echo "========================================="
        echo "Commands: ${{ inputs.sbt-commands }}"
        echo "SBT_OPTS: $SBT_OPTS"
        echo ""
        
        # Run SBT commands
        echo "Executing: sbt ${{ inputs.sbt-commands }}"
        echo ""
        
        if sbt ${{ inputs.sbt-commands }}; then
          echo ""
          echo "========================================="
          echo "✓ Build Successful"
          echo "========================================="
          echo "status=success" >> $GITHUB_OUTPUT
        else
          EXIT_CODE=$?
          echo ""
          echo "========================================="
          echo "✗ Build Failed (exit code: $EXIT_CODE)"
          echo "========================================="
          echo "status=failure" >> $GITHUB_OUTPUT
          exit $EXIT_CODE
        fi
    
    # ========================================
    # Display Build Results
    # ========================================
    - name: Display Build Information
      if: always()
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "========================================="
        echo "Build Information"
        echo "========================================="
        
        if [ -f "build.sbt" ]; then
          echo "build.sbt:"
          cat build.sbt | head -20
          echo ""
        fi
        
        echo "Generated Artifacts:"
        find . -path "*/target/universal/*.zip" -type f 2>/dev/null | while read file; do
          size=$(du -h "$file" | cut -f1)
          echo "  - $file ($size)"
        done || echo "  No ZIP artifacts found"
        
        echo ""
        echo "Build Status: ${{ steps.build.outputs.status }}"
    
    # ========================================
    # Generate Artifact Name
    # ========================================
    - name: Generate Artifact Name
      id: generate-artifact-name
      if: inputs.upload-artifacts == 'true'
      shell: bash
      run: |
        echo "========================================="
        echo "Generating Artifact Name"
        echo "========================================="
        
        # Determine prefix
        if [ -n "${{ inputs.artifact-name-prefix }}" ]; then
          PREFIX="${{ inputs.artifact-name-prefix }}"
        else
          # Use repository name as prefix
          PREFIX="${{ github.event.repository.name }}"
        fi
        
        # Generate random suffix (10 alphanumeric chars like mktemp -u XXXXXXXXXX)
        RANDOM_SUFFIX=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 10)
        
        # Combine prefix and suffix
        ARTIFACT_NAME="${PREFIX}-${RANDOM_SUFFIX}"
        
        echo "Prefix: $PREFIX"
        echo "Random Suffix: $RANDOM_SUFFIX"
        echo "Generated Artifact Name: $ARTIFACT_NAME"
        echo ""
        
        echo "artifact-name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT
    
    # ========================================
    # Upload Artifacts to GitHub Actions
    # ========================================
    - name: Upload Build Artifacts
      if: inputs.upload-artifacts == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.generate-artifact-name.outputs.artifact-name }}
        path: ${{ inputs.artifact-path }}
        if-no-files-found: ${{ inputs.artifact-if-no-files-found }}
        retention-days: ${{ inputs.artifact-retention-days }}
    
    # ========================================
    # Set Upload Status
    # ========================================
    - name: Set Upload Status
      id: set-upload-status
      if: always()
      shell: bash
      run: |
        if [ "${{ inputs.upload-artifacts }}" == "true" ]; then
          echo "uploaded=true" >> $GITHUB_OUTPUT
          echo "✓ Artifacts uploaded successfully"
        else
          echo "uploaded=false" >> $GITHUB_OUTPUT
          echo "ℹ Artifact upload disabled"
        fi
    
    # ========================================
    # Display Summary
    # ========================================
    - name: Display Build Summary
      if: always()
      shell: bash
      run: |
        echo ""
        echo "========================================="
        echo "Build and Test Summary"
        echo "========================================="
        echo "Build Status: ${{ steps.build.outputs.status }}"
        echo "SBT Version: ${{ steps.setup-sbt.outputs.sbt-version }}"
        echo "Cache Hit: ${{ steps.setup-sbt.outputs.cache-hit }}"
        
        if [ "${{ inputs.upload-artifacts }}" == "true" ]; then
          echo "Artifact Name: ${{ steps.generate-artifact-name.outputs.artifact-name }}"
          echo "Artifact Uploaded: ${{ steps.set-upload-status.outputs.uploaded }}"
        else
          echo "Artifact Upload: Disabled"
        fi
        
        echo "========================================="
        
        if [ "${{ steps.build.outputs.status }}" == "success" ]; then
          echo "✓✓✓ Build and Test Completed Successfully ✓✓✓"
        else
          echo "✗✗✗ Build and Test Failed ✗✗✗"
        fi
        
        echo "========================================="

branding:
  icon: 'package'
  color: 'blue'
