#!/bin/bash
set -e

# ========================================
# Configure Artifactory Credentials Script
# ========================================
# This script creates credential files for SBT
# to authenticate with Artifactory
# ========================================

echo "=== Configuring Artifactory Credentials ==="

# Get parameters from environment
CREDENTIALS_REALM="${CREDENTIALS_REALM:-Artifactory Realm}"
CREDENTIALS_HOST="${CREDENTIALS_HOST:-}"

# Get credentials from environment variables
ARTIFACTORY_USER="${ARTIFACTORY_USER:-}"
ARTIFACTORY_PASSWORD="${ARTIFACTORY_PASSWORD:-}"
ARTIFACTORY_API_KEY="${ARTIFACTORY_API_KEY:-}"

echo "Realm: $CREDENTIALS_REALM"
echo "Host: $CREDENTIALS_HOST"
echo ""

# Validate inputs
if [ -z "$CREDENTIALS_HOST" ]; then
  echo "ERROR: CREDENTIALS_HOST is empty"
  echo "Please provide credentials-host input"
  exit 1
fi

# Check if credentials are available
if [ -z "$ARTIFACTORY_USER" ]; then
  echo "ERROR: ARTIFACTORY_USER environment variable is not set"
  echo "Please set ARTIFACTORY_USER (from Vault or GitHub Secrets)"
  exit 1
fi

# Determine which credential to use (API Key or Password)
CREDENTIAL=""
CREDENTIAL_TYPE=""

if [ -n "$ARTIFACTORY_API_KEY" ]; then
  CREDENTIAL="$ARTIFACTORY_API_KEY"
  CREDENTIAL_TYPE="API Key"
elif [ -n "$ARTIFACTORY_PASSWORD" ]; then
  CREDENTIAL="$ARTIFACTORY_PASSWORD"
  CREDENTIAL_TYPE="Password"
else
  echo "ERROR: Neither ARTIFACTORY_API_KEY nor ARTIFACTORY_PASSWORD is set"
  echo "Please set one of these environment variables (from Vault or GitHub Secrets)"
  exit 1
fi

echo "Using credential type: $CREDENTIAL_TYPE"
echo "Username: $ARTIFACTORY_USER"
echo ""

# ========================================
# Create Ivy2 credentials file
# ========================================
echo "=== Creating Ivy2 Credentials ==="

IVY2_DIR="$HOME/.ivy2"
IVY2_CREDENTIALS="$IVY2_DIR/.credentials"

mkdir -p "$IVY2_DIR"

cat > "$IVY2_CREDENTIALS" <<EOF
realm=${CREDENTIALS_REALM}
host=${CREDENTIALS_HOST}
user=${ARTIFACTORY_USER}
password=${CREDENTIAL}
EOF

# Secure the file
chmod 600 "$IVY2_CREDENTIALS"

echo "✓ Ivy2 credentials written to: $IVY2_CREDENTIALS"

# ========================================
# Create SBT credentials file
# ========================================
echo ""
echo "=== Creating SBT Credentials ==="

SBT_PLUGINS_DIR="$HOME/.sbt/1.0/plugins"
SBT_CREDENTIALS="$SBT_PLUGINS_DIR/credentials.sbt"

mkdir -p "$SBT_PLUGINS_DIR"

cat > "$SBT_CREDENTIALS" <<EOF
// Auto-generated credentials for Artifactory
// Generated by setup-sbt action

import sbt._

credentials += Credentials(
  "${CREDENTIALS_REALM}",
  "${CREDENTIALS_HOST}",
  sys.env.getOrElse("ARTIFACTORY_USER", "${ARTIFACTORY_USER}"),
  sys.env.getOrElse("ARTIFACTORY_API_KEY", 
    sys.env.getOrElse("ARTIFACTORY_PASSWORD", "${CREDENTIAL}"))
)
EOF

# Secure the file
chmod 600 "$SBT_CREDENTIALS"

echo "✓ SBT credentials written to: $SBT_CREDENTIALS"

# ========================================
# Verification
# ========================================
echo ""
echo "=== Verification ==="

echo "Checking Ivy2 credentials file..."
if [ -f "$IVY2_CREDENTIALS" ]; then
  echo "  ✓ File exists: $IVY2_CREDENTIALS"
  echo "  ✓ File size: $(wc -c < "$IVY2_CREDENTIALS") bytes"
else
  echo "  ✗ File not found: $IVY2_CREDENTIALS"
  exit 1
fi

echo "Checking SBT credentials file..."
if [ -f "$SBT_CREDENTIALS" ]; then
  echo "  ✓ File exists: $SBT_CREDENTIALS"
  echo "  ✓ File size: $(wc -c < "$SBT_CREDENTIALS") bytes"
else
  echo "  ✗ File not found: $SBT_CREDENTIALS"
  exit 1
fi

echo ""
echo "✓✓✓ Artifactory credentials configured successfully ✓✓✓"
echo ""
echo "Note: Credentials are stored in:"
echo "  - $IVY2_CREDENTIALS (Ivy2 format)"
echo "  - $SBT_CREDENTIALS (SBT format)"
